# Generated by Django 5.2 on 2025-04-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientcoin',
            unique_together={('client', 'coin')},
        ),
        migrations.AlterUniqueTogether(
            name='clientwallet',
            unique_together={('client', 'wallet')},
        ),
    ]
