# Generated by Django 5.2 on 2025-04-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clientcoin_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='logo',
            field=models.URLField(blank=True, verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(blank=True, max_length=255, verbose_name='Символ'),
        ),
    ]
