# Generated by Django 5.2 on 2025-04-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_coin_logo_alter_coin_name_alter_coin_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcoin',
            name='tracking_param',
            field=models.CharField(blank=True, choices=[('price_up', 'Цена повышается'), ('price_down', 'Цена понижается')], max_length=100, verbose_name='Параметр отслеживания'),
        ),
    ]
