# Generated by Django 5.2 on 2025-04-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clientcoin_tracking_price_coin_chain_wallet_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='TxHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='coin',
            options={'ordering': ['symbol'], 'verbose_name': 'Монета', 'verbose_name_plural': 'Монеты'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['address'], 'verbose_name': 'Кошелёк', 'verbose_name_plural': 'Кошельки'},
        ),
    ]
