# Generated by Django 5.2 on 2025-05-03 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transaction_delete_txhash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcoin',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отслеживаемая монета', 'verbose_name_plural': 'Отслеживаемые монеты'},
        ),
        migrations.AlterModelOptions(
            name='clientwallet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отслеживаемый кошелёк', 'verbose_name_plural': 'Отслеживаемые кошельки'},
        ),
        migrations.AddField(
            model_name='clientcoin',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Уведомление отправлено'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.coin', verbose_name='Монета'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.wallet', verbose_name='Кошелёк'),
        ),
    ]
