# Generated by Django 5.2 on 2025-05-04 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_clientcoin_options_alter_clientwallet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientwallet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отслеживаемый кошелек', 'verbose_name_plural': 'Отслеживаемые кошельки'},
        ),
        migrations.AlterField(
            model_name='clientcoin',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='core.client', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='clientcoin',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.coin', verbose_name='Монета'),
        ),
        migrations.AlterField(
            model_name='clientwallet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='core.client', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='clientwallet',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.wallet', verbose_name='Кошелек'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.coin', verbose_name='Монета'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coin_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество монет'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coin_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена токена'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(blank=True, max_length=255, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.wallet', verbose_name='Кошелёк'),
        ),
    ]
