# Generated by Django 5.2 on 2025-05-05 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_clientwallet_options_alter_clientcoin_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='max_coin_creation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Максимальная дата создания монеты'),
        ),
        migrations.AddField(
            model_name='client',
            name='max_coin_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимальная цена монеты'),
        ),
        migrations.AddField(
            model_name='client',
            name='min_coin_market_cap',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Минимальная капитализация монеты'),
        ),
        migrations.AddField(
            model_name='coin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 10, 3, 57, 611557), verbose_name='Дата создания монеты'),
            preserve_default=False,
        ),
    ]
