# Generated by Django 5.2 on 2025-05-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_client_max_coin_creation_date_client_max_coin_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='max_coin_creation_date',
        ),
        migrations.AddField(
            model_name='client',
            name='min_coin_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальный возраст монеты'),
        ),
    ]
