# Generated by Django 5.2 on 2025-05-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_client_max_coin_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcoin',
            name='tracking_price',
        ),
        migrations.AddField(
            model_name='client',
            name='max_coin_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальный возраст монеты'),
        ),
        migrations.AddField(
            model_name='clientcoin',
            name='percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отслеживаемое изменение цены в %'),
        ),
        migrations.AddField(
            model_name='clientcoin',
            name='start_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Начальная цена'),
        ),
    ]
