# Generated by Django 5.2 on 2025-05-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_clientcoin_tracking_price_client_max_coin_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='pair_address',
            field=models.CharField(default='blank', max_length=255, verbose_name='Адрес пула'),
            preserve_default=False,
        ),
    ]
