# Generated by Django 5.2 on 2025-05-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_coin_pair_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coin',
            unique_together={('address', 'chain')},
        ),
    ]
