# Generated by Django 5.2 on 2025-06-06 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_coin_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFilters',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.client')),
                ('min_liquidity', models.FloatField(verbose_name='Ликвидность')),
                ('min_price', models.FloatField(blank=True, null=True, verbose_name='Мин. цена')),
                ('max_price', models.FloatField(blank=True, null=True, verbose_name='Макс. цена')),
                ('min_age', models.IntegerField(default=0, verbose_name='Мин. возраст')),
                ('max_age', models.IntegerField(blank=True, null=True, verbose_name='Мин. возраст')),
                ('min_market_cap', models.IntegerField(default=0, verbose_name='Капитализация')),
                ('results', models.JSONField(verbose_name='Результаты')),
            ],
            options={
                'verbose_name': 'Фильтры пользователя',
                'verbose_name_plural': 'Фильтры пользователей',
            },
        ),
    ]
