# Generated by Django 5.2 on 2025-06-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_clientfilters'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfilters',
            name='offset',
            field=models.IntegerField(default=0, verbose_name='Смещение'),
        ),
    ]
